### ISSUE TITLE
Router doesn't behave well with async routes on server

### ISSUE THREAD

**Issue by 03eltond** [denvned/isomorphic-relay-router#27] opened 2016-04-28 02:09 UTC
Hello!  I've noticed the Router will fail to render on the server when using async routes.  This seems to be a new behavior since the last release.  I think the issue may actually be in how react-router works on the server, but I'm not entirely sure.

If you modify routes.js in your todo example to use getComponent():

``` javascript
        childRoutes: [
            {
                path: ':status',
                //component: TodoList,
                getComponent: (nextState, cb) => {
                    setTimeout(() => {
                        cb(null, TodoList);
                    });
                },
                queries: ViewerQueries,
            },
        ],
```

The app will break.  The output from ReactDOMServer.renderToString() results in .  If you remove the setTimeout lines, the app works again since it is again synchronous.  In our app, we are actually using the other async methods getIndexRoute() and getChildRoutes(), with the same result.

When debugging the problem, I found that Router.js:render():148 (https://github.com/reactjs/react-router/blob/master/modules/Router.js#L148) returns early due to this.state.location == null.  Then, at a later time in an event listener after the async work is done at Router.js.render():77 (https://github.com/reactjs/react-router/blob/master/modules/Router.js#L77), the component state is set.  On the client, this would trigger a rerender, but on the server, I think it is too late and the server will not execute render again.

I may dig into this a bit more tomorrow, but wanted to raise the issue and see if you had any thoughts.  If this issue actually belongs on react-router please let me know and I'll post it there.

Thanks!

**Comment by denvned** [comment] 2016-04-30 06:58
@03eltond The cause of this issue is probably the same as in #26, and was fixed in v0.7.0-beta.1. Can you confirm it?

**Comment by 03eltond** [comment] 2016-04-30 15:54
I think that issue is similar, but a little different.  I was actually having that issue too, but it went away with the fix in beta 1.  When the changes I outlined above are made, it also throws the error "React DOM tree root should always have a node reference".  There is an open issue in React issues where I have posted [this same information here](https://github.com/facebook/react/issues/6232#issuecomment-215478852).

The problem, I think, boils down to the components and data all need to be ready to go by the time renderToString() is called.  In the thread I posted, the react-router guys suggest we should be using RouterContext instead of Router, because match() has already done the async routing and we can use RouterContext directly which will not resolve the async routes a second time.  Since we are also using Relay, I tried using [react-router-relay's RouterContext](https://github.com/relay-tools/react-router-relay/blob/master/src/RelayRouterContext.js), but that didn't seem to work either.  I'm still kind of poking around on it though, I'll post back if I can figure something out.

**Comment by denvned** [comment] 2016-04-30 21:03
@03eltond, `<Router>` when wrapped in `match` can be used on the server, so it is not the problem. And I've found that the root cause for both this issue, and for #26 is actually the same. But the problem is that the workaround for #26 used in v0.7.0-beta.1 while solving #26 doesn't solve this issue. However, the proper [fix](https://github.com/reactjs/react-router/pull/3394) for #26 would solve the both issues; it is pity it was rejected. 😞

**Closed as completed** 2016-05-01 06:24 UTC
Labels: bug

**Comment by denvned** [comment] 2016-05-01 08:42
@03eltond, v0.8.0-beta.0 fixes this issue, but note that API was slightly changed, see README.

**Comment by 03eltond** [comment] 2016-05-02 16:14
Thanks a bunch @denvned, we really appreciate your work on this project.  This fix does indeed solve our problem.  I'll be watching with interest on the open issue in react-router.  I agree that it would be nice if we could converge the code paths.
